### PR TITLE
Add React range to react-addons-shallow-compare

### PR DESCRIPTION
**Pull request by redonkulus**
@kfay @mridgway

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by roderickhsiao** [comment]
:+1:

**Comment by kfay** [comment]
:+1:

**Pull request merged**
